# Generated by Django 5.0.6 on 2026-08-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="passing_marks",
            field=models.PositiveIntegerField(default=35),
        ),
    ]
